name: Bump Release Version

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  bump-version:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Version Tag
        id: tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          MAJOR_STRING_TOKEN: break
          MINOR_STRING_TOKEN: feat
          PATCH_STRING_TOKEN: fix

      - name: Publish Release Automaticcally
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          draft: false
          prerelease: false
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: "${{ steps.tag.outputs.tag }}"
          automatic_release_tag: ${{ steps.tag.outputs.new_tag }}